[sparrow]
tag = "uuid as str"
private_key = "str"
created_at = "datetime in utc"
version = "version no. as str"

[servers]

[servers.example]
ip = "ip as str"
port = "int"
alias = "str"
joined_at = "datetime in utc"
is_online = "bool"
user_connected = "bool"
